apiVersion: v1
kind: Namespace
metadata:
  name: education
---
apiVersion: v1
kind: Namespace
metadata:
  name: research
---
apiVersion: v1
kind: Namespace
metadata:
  name: finance
---
apiVersion: v1
kind: Namespace
metadata:
  name: aegismesh-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring